### PR TITLE
Feature/integrate relations

### PR DESCRIPTION
**Pull request by syncall**

### CODE REVIEW

**Comment by demirdagemir** [comment]
You were 5 commits behind develop, I pulled to your branch and resolved the conflicts. (kept your changes.)

Also this could be the reason why you couldn't see redux.

**Review by demirdagemir — CHANGES_REQUESTED** [review]
I couldn't understand what you did with the logo, it seems completely broken now. Shall we revert it to the old one, and worry about it later? Maybe create a seperate issue for that.

**Comment by syncall** [comment]
Yes I'll revert the logo. But it was always broken on my laptop... Setting the width to 100% would at least solve the cutt off.
unbenannt
on a small screen (mobile) it looks like that:
unbenannt

**Comment by demirdagemir** [comment]
Probably it's an svg issue. Maybe I'll create a png instead later on, for the time being.

**Comment by kordianbruck** [comment]
Guys, please speed this up. This is a fairly small PR and we are getting close to it being open for a week! :racehorse:

**Comment by syncall** [comment]
I know, but I am also ill for more than half a week now. The feature is finished, just needs to be merged.

**Comment by pfent** [comment]
paging @demirdagemir for review and merging

**Review by demirdagemir — APPROVED** [review]
🔥

**Pull request merged**
