### PR TITLE
Feature/header footer

### PR DESCRIPTION
**Pull request by demirdagemir**
Clean-up CSS on Landing page, fix styles on header, footer, add minimal css animations

### CODE REVIEW

**Review by syncall — COMMENTED** [review]
I don't think this will work. Have you tried to load for example the about or legal page?

**Comment by demirdagemir** [comment]
What do you mean? It doesn't load or does it take too long?

**Comment by syncall** [comment]
Haven't tried it but from looking at the code the header should disappear

**Comment by sacdallago** [comment]
@syncall the jedi

**Review by syncall — APPROVED** [review]
Yay

**Comment by kordianbruck** [comment]
Cool :tada:

**Pull request merged**
