### PR TITLE
Add styles to home page and add search component

### PR DESCRIPTION
**Pull request by demirdagemir**

### CODE REVIEW

**Comment by kordianbruck** [comment]
Instead of writing prefixes yourself there is a great prefixing plugin for webpack: https://github.com/postcss/postcss-loader

Might reduce the amount of scss you need to write

**Comment by pfent** [comment]
Could you add credits / a license for the photo?

**Comment by demirdagemir** [comment]
@pfent It was license free and said no attribution required, you can check it out here: https://www.pexels.com/photo/orchestra-instruments-on-platform-62461/

**Comment by pfent** [comment]
Nevertheless, it's good practice to *document*, what license resources have, where you are not the copyright holder.

**Review by syncall — APPROVED** [review]
Wow, looks very cool!

**Comment by syncall** [comment]
maybe add the link, from where the photos are? https://unsplash.com/license

**Pull request merged**
