### PR TITLE
Feature/elastic search server

### PR DESCRIPTION
**Pull request by syncall**
The Elastic Search Server with the REST API for Querying datasets. Already included sample data

### CODE REVIEW

**Comment by pfent** [comment]
Uhmm…
Are you sure, you want to commit 190 files, including binaries?

**Comment by pfent** [comment]
You might wanna sneak a peek, how [the other team](https://github.com/MusicConnectionMachine/VisualizationG5/pull/15) set up elasticsearch

**Comment by chaoran-chen** [comment]
Hey. I think that another, interim way could be to only upload Elasticsearch/data and Elasticsearch/conf to github. It still contains binaries but might be a simple solution to share the setup with the others in the early development phase.

**Comment by syncall** [comment]
You are right, docker is here probably the better way. @demirdagemir You can still use the branch right now to get the search page running. The API will not change.

**Comment by sacdallago** [comment]
So close this? I fear the worst :D

**Comment by syncall** [comment]
@sacdallago I am not sure what the best thing is right now. Because all the configuration files for elastic search are stored in the binaries I dont know how to properly share them with the team...
I have build now a custom image for Elasticsearch, containing the configuration and sample data. Should I upload this to docker? In the same repository as Group 5?

**Comment by syncall** [comment]
This would just be a setup for early development until we have a persistent backend.. Other question, do we get this backend later or is it the job of Team A?

**Comment by sacdallago** [comment]
@syncall I'm sure about one thing: the binaries should **not** make it into develop.

> Because all the configuration files for elastic search are stored in the binaries I dont know how to properly share them with the team...

I don't understand _what_ configuration files? If you can't share them in not-binarized-form, I have a hard time believing they are configuration related 💭  If it's stuff that makes elasearch work, this will already be contained in the *cough* docker container 😆 
Docker exists because you don't need to run the server locally anymore (at least not in production, testing, or semi-production environment), but you can run the docker container, which contains the server and all the data you need.

> I have build now a custom image for Elasticsearch, containing the configuration and sample data. Should I upload this to docker? In the same repository as Group 5?

You can set up an automatic built on docker hub similarly to the other group, but not in the same dockerhub. You will probably need to be added to the dockerhub organization, for which you might want to give your docker username to @chaoran-chen 

And no, you have not created a custom image :) you have just created a `docker-compose`, you need to create a `Dockerfile` to create a custom image.


Anyway, if I may: All your problems seem to stem from the fact that you haven't fully understood how to use docker. I can tell that by looking at [this line](https://github.com/MusicConnectionMachine/VisualizationG6/pull/14/files#diff-4e5e90c6228fd48698d074241c2ba760R24)

You are not supposed to just create a docker-compose file taking images from a standard source as is and then push in your stuff in. You create a container that starts from a standard source, and you build your data and tool inside the container by running the scripts that you would run locally to create that data. In other words, the `Dockerfile` should emulate the steps that you needed to fire up the elastic search server in the first place. Did you `curl` the data from somwhere? Good. Than you need to add that to the dockerfile. Did you need to `npm install` stuff, good: than that goes into the `Dockerfile` as well.

**Comment by syncall** [comment]
@sacdallago thanks for the big reply 😄 I am slowly understanding docker though..

> If you can't share them in not-binarized-form, I have a hard time believing they are configuration related

Its similar to a databse. Table configuration, passwords etc are stored inside sql tables, which are stored binary. Normaly this is the data, that shoul not change and thus should not be in a docker image... but I dont't know how to share the test server with my team mates in another way..

> And no, you have not created a custom image

I have, didn't commit the code yet, sry.

Yeah I'll try to put everything inside the Dockerfile. Just have to figure out a way to execute a script after elastic search has started..

**Comment by chaoran-chen** [comment]
This is how we check if Elasticsearch is available:
https://github.com/MusicConnectionMachine/VisualizationG5/blob/develop/express/start-dev.sh#L3

**Comment by syncall** [comment]
Thanks @chaoran-chen that actually works 👍

**Comment by pfent** [comment]
@chaoran-chen You might want to do something like:
```bash
timeout 10 bash -c -- 'while ! curl http://elasticsearch:9200; do sleep 1; done;' || echo "timed out" 
```

So you don't loop forever, when there's something wrong with elasticsearch

**Comment by kordianbruck** [comment]
You still have `elastic_data.zip` in the diff. Is that still required? 

Please make sure you `Squash and merge` instead of `merge` so that all of those binaries do not end up in the Git history.

**Comment by syncall** [comment]
I've tried to get it running without the data dir. But loading them through curl every time was super slow inside docker. And even then it didn't work properly..

Do we get a server later on, where we can deploy the image to? Then this would be no problem anymore.

**Comment by kordianbruck** [comment]
Right. Well not great but if it works...

Yes, we have infrastructure up and coming in the next weeks. I don't think students will get access tho. @sacdallago knows more

**Comment by sacdallago** [comment]
Yeah the idea is to have docker's automatic builds on docker hub set up, and when a new build is available (every time there is a merge on develop/master) the new docker image gets fetched on the production server, and the service redeployed.

That it _takes long_ is not a problem! The idea is that it's completely self sufficient, to so say :)

You might want to differ the actual data fetching to when the docker container is run. Why?

1. When you **build** the container, you want a blueprint of a system where your project **will** run (something lightweight, that you can toss around without needing to download 4GB of container)
2. When you **run** the container, you want the complete system, and if it's a database, you want the system with all it's data

To do this, you can use a bash script as `CMD` directive in the `Dockerfile`, that will look something like:

```bash
IF someFolder -> Exists?
  # Do nothing
ELSE 
  curl someData --> someFolder
  unzip someFolder/someData
  ...


node elasticSearch.js

exit 0
```

**Comment by syncall** [comment]
Thatsa what I did, but it took elasticsearch hours to finish the script.
But it worked now to start elastisearch directly in the Dockerfile. Now he finishes building in under a minute. No idea why..

**Review by demirdagemir — APPROVED** [review]

**Pull request merged**
