### PR TITLE
Delete deprecated elastic search folder

### PR DESCRIPTION
**Pull request by demirdagemir**
Delete deprecated folder as it is not used after travis and docker cloud has already been set up

### CODE REVIEW

**Comment by demirdagemir** [comment]
@syncall Just deleting the deprecated folder. We don't need this anymore, right?

**Comment by syncall** [comment]
Not so sure. At the point where we actually query the other teams we don't need it anymore. If the data inside the docker container get lost somhow (Someone deletes the container in Dockerhub etc.) we would need it.

**Comment by demirdagemir** [comment]
You can approve then, we have it on git, also I keep a local copy(you can also). The size is too big and I think it's better we don't store it here.

**Review by syncall — APPROVED** [review]
yeah u are right

**Pull request merged**
