### PR TITLE
searchbar placeholder changed

### LINKED ISSUE #89: Title for the search bar
Replace "search for something" with "search for composers, musicians and music works"

### PR DESCRIPTION
**Pull request by ysdevys**
placeholder changed

fixes #89

### CODE REVIEW

**Review by syncall — CHANGES_REQUESTED** [review]
The string is too long. Did you test this? But it's true it's better than something.

**Comment by syncall** [comment]
Ah sorry didn't see the issue. But its really a problem. The long string can not be displayed in the small input field. Not sure what to do there. Because increasing the size breaks the responsiveness.(because the browser won't change the width automatically depending on screen size anymore)
@goldbergtatyana

**Comment by syncall** [comment]
@ysdevys maybe this works. https://www.w3schools.com/bootstrap/bootstrap_forms_sizing.asp
But when you try it, also try to scale the browser size down and have a look at how it would look on a mobile device.
But I think the text is still too long.

**Comment by goldbergtatyana** [comment]
Valid points, @syncall !

How about then replacing the long string with "Search..."

And then we specify below the search bar what can be searched for:
"Search for composers, music works and musicians"

**Review by syncall — APPROVED** [review]
Works

**Pull request merged**
