### PR TITLE
Feature/merge deps g5

### PR DESCRIPTION
**Pull request by ysdevys**
dependencies from G5 merged in package.json

### CODE REVIEW

**Comment by ysdevys** [comment]
broken build fixed

**Comment by syncall** [comment]
Maybe we don't need all dependencies? Just the ones used in the three widgets. So everything for the build process etc could be skipped?

**Comment by kordianbruck** [comment]
Not sure, we still need to build their stuff into ours no?

**Comment by chaoran-chen** [comment]
Fixed in #112

**Pull request closed without merging**
